---
# handlers file for nuc

- name: Restart Nginx systemd service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: Restart Monit systemd service
  ansible.builtin.systemd:
    name: monit
    state: restarted
  become: true

- name: Reboot and wait
  ansible.builtin.reboot:
