---
# control group_vars
k3s_control_node: true
k3s_server:
  node-taint:
    - "node-role.kubernetes.io/master=true:NoSchedule"
  node-ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tls-san:
    - "{{ kube_vip_address }}"
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  disable:
    - traefik
    - servicelb
    - local-storage
k3s_server_manifests_urls:
  # https://github.com/kube-vip/kube-vip
  # kube-vip rbac - https://kube-vip.io/docs/usage/k3s/#step-2-upload-kube-vip-rbac-manifest
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
  # kube-vip cloud controller - https://kube-vip.io/docs/usage/cloud-provider/
  # https://github.com/kube-vip/kube-vip-cloud-provider
  - url: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/v0.0.9/manifest/kube-vip-cloud-controller.yaml
    filename: kube-vip-cloud-controller.yaml
k3s_server_manifests_templates:
  - ../templates/kube-vip-daemonset.yml.j2
  - ../templates/kubevip-configmap.yml.j2
