op_ssh_vault_name            = ""
op_ssh_key_name              = ""
virtual_environment_password = ""
vm_name                      = ""
vm_ip                        = ""
vm_username                  = ""
vm_password                  = ""
