version: "3"

vars:
  VENV_PATH: "~/.virtualenvs/home-ops"

tasks:
  op:vault:
    desc: |
      Ensure the op-ansible-vault.sh script is executable.
    internal: true
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - chmod +x op-ansible-vault.sh
    preconditions:
      - sh: test -f op-ansible-vault.sh
        msg: op-ansible-vault.sh file does not exist {{.USER_WORKING_DIR}}.

  venv:build:
    desc: Build Python virtual environment
    internal: true
    cmds:
      - mkdir -pv $(dirname {{.VENV_PATH}})
      - python -m venv {{.VENV_PATH}}
      - "{{.VENV_PATH}}/bin/pip install --upgrade pip"
      - "{{.VENV_PATH}}/bin/pip install -r {{.USER_WORKING_DIR}}/requirements.txt"

  venv:
    desc: Create Python virtual environment in {{.VENV_PATH}}
    cmds:
      - task: venv:build

  ansible:hosts:
    desc: List Ansible hosts
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: op:vault
      - "{{.VENV_PATH}}/bin/ansible all --list-hosts"
    preconditions:
      - sh: command -v {{.VENV_PATH}}/bin/ansible
        msg: ansible is not installed. Have you ran 'task venv'?

  ansible:adhoc:
    desc: |
      Run Ansible adhoc command.
      Example: task ansible:adhoc -- proxmox -m ping
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: op:vault
      - "{{.VENV_PATH}}/bin/ansible {{.CLI_ARGS}}"
    preconditions:
      - sh: command -v {{.VENV_PATH}}/bin/ansible
        msg: ansible is not installed. Have you ran 'task venv'?

  ansible:play:
    desc: |
      Run Ansible playbook.
      Example: task ansible:play -- playbooks/minecraft-playbook.yml
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: op:vault
      - "{{.VENV_PATH}}/bin/ansible-playbook {{.CLI_ARGS}}"
    preconditions:
      - sh: command -v {{.VENV_PATH}}/bin/ansible-playbook
        msg: ansible-playbook is not installed. Have you ran 'task venv'?

  ansible:encrypt:
    desc: |
      Encrypt Ansible variable.
      Example: task ansible:encrypt -- 'Secret!' --name 'my_secret'
    interactive: true
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: op:vault
      - "{{.VENV_PATH}}/bin/ansible-vault encrypt_string {{ .CLI_ARGS }}"
    preconditions:
      - sh: command -v {{.VENV_PATH}}/bin/ansible-vault
        msg: ansible-vault is not installed. Have you ran 'task venv'?

  ansible:requirements:
    desc: Install Ansible requirements
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - "{{.VENV_PATH}}/bin/ansible-galaxy install {{ .CLI_ARGS }} -r requirements.yml"
    preconditions:
      - sh: command -v {{.VENV_PATH}}/bin/ansible-galaxy
        msg: ansible-galaxy is not installed. Have you ran 'task venv'?
      - sh: test -f requirements.yml
        msg: requirements.yml does not exist.

  tools:
    desc: Install tooling
    cmds:
      - brew install {{.TOOLS}}
      - brew install --cask {{.CASKS}}
    preconditions:
      - sh: command -v brew
        msg: Homebrew is not installed. See https://brew.sh/
    vars:
      TOOLS: >-
        fluxcd/tap/flux
        sops
        age
        helm
        jq
        yq
        kubernetes-cli
        kustomize
        gettext
        pyenv
      CASKS: >-
        1password-cli
        orbstack
