version: "3"

vars:
  ANSIBLE_VERSION: "8.5.0"

tasks:
  ansible:hosts:
    desc: List Ansible hosts
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: venv:source
      - ansible all --list-hosts

  ansible:adhoc:
    desc: |
      Run Ansible adhoc command.
      Example: task ansible:adhoc -- -m ping
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: venv:source
      - ansible all {{.CLI_ARGS}}

  ansible:play:
    desc: |
      Run Ansible playbook.
      Example: task ansible:play -- playbooks/minecraft-playbook.yml
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: venv:source
      - ansible-playbook {{.CLI_ARGS}}

  ansible:encrypt:
    desc: |
      Encrypt Ansible variable.
      Example: task ansible:encrypt -- 'Secret!' --name 'my_secret'
    dir: "{{.USER_WORKING_DIR}}"
    interactive: true
    cmds:
      - chmod +x op-ansible-vault.sh
      - task: venv:source
      - ansible-vault encrypt_string {{ .CLI_ARGS }}
    preconditions:
      - sh: test -f op-ansible-vault.sh
        msg: op-ansible-vault.sh file does not exist.

  ansible:requirements:
    desc: Install Ansible requirements
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: venv:source
      - ansible-galaxy install --force -r requirements.yml
    preconditions:
      - sh: command -v ansible-galaxy
        msg: ansible-galaxy is not installed. Have you ran `task venv`?
      - sh: test -f requirements.yml
        msg: requirements.yml does not exist.

  venv:source:
    desc: Source Python virtual environment
    internal: true
    cmds:
      - source ~/.virtualenvs/$(basename {{.USER_WORKING_DIR}})/bin/activate
    preconditions:
      - sh: test -f ~/.virtualenvs/$(basename {{.USER_WORKING_DIR}})/bin/activate
        msg: Python virtual environment not found. Have you ran `task venv`?

  venv:build:
    desc: Build Python virtual environment
    internal: true
    cmds:
      - mkdir -pv ~/.virtualenvs
      - python -m venv ~/.virtualenvs/$(basename {{.USER_WORKING_DIR}})
      - ~/.virtualenvs/$(basename {{.USER_WORKING_DIR}})/bin/pip install --upgrade pip
      - ~/.virtualenvs/$(basename {{.USER_WORKING_DIR}})/bin/pip install ansible=={{.ANSIBLE_VERSION}}

  venv:
    desc: Create Python virtual environment
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: venv:build

  tools:
    desc: Install tooling
    cmds:
      - brew install {{.TOOLS}}
      - brew install --cask {{.CASKS}}
    preconditions:
      - sh: command -v brew
        msg: Homebrew is not installed. See https://brew.sh/
    vars:
      TOOLS: >-
        fluxcd/tap/flux
        sops
        age
        helm
        jq
        yq
        kubernetes-cli
        kustomize
        gettext
        pyenv
      CASKS: >-
        1password-cli
        orbstack
