---
version: "3"

tasks:
  venv:
    desc: Create the Python virtual environment using uv.
    cmd: "uv sync {{ .CLI_ARGS }}"

  ansible:requirements:
    desc: Generate Ansible EE Python requirements.txt.
    cmds:
      - uv sync --group build
      - uv run python ansible/ee/build_requirements.py

  ansible:install:requirements:
    desc: Install Ansible requirements locally.
    cmds:
      - uv add -r ansible/ee/requirements.txt
      - "uv run ansible-galaxy install -r ansible/ee/requirements.yml {{
        .CLI_ARGS }}"

  ansible:build:
    desc: Build the Ansible Execution Environment.
    cmds:
      - uv sync --group build
      - uv --directory ansible/ee run ansible-builder build --container-runtime
        docker --tag ghcr.io/dbrennand/home-ops:latest -vvv
