version: "3"

vars:
  PROJECT_ROOT:
    sh: git rev-parse --show-toplevel
  VENV_PATH: "{{ .PROJECT_ROOT }}/ansible/.venv"
  ANSIBLE_PROJECT_PATH: "{{ .PROJECT_ROOT }}/ansible"

tasks:
  venv:
    desc: Create the Python virtual environment using uv.
    dir: "{{ .ANSIBLE_PROJECT_PATH }}"
    cmd: "uv sync {{ .CLI_ARGS }}"

  ansible:requirements:
    desc: Install Ansible requirements.
    dir: "{{ .ANSIBLE_PROJECT_PATH }}"
    cmds:
      - uv add -r ee/requirements.txt
      - "uv run ansible-galaxy install -r ee/requirements.yml {{ .CLI_ARGS }}"
    preconditions:
      - sh: command -v {{ .VENV_PATH }}/bin/ansible-galaxy
        msg: ansible-galaxy is not installed. Have you ran 'task venv'?

  ansible:ee:
    desc: Build the Ansible Execution Environment.
    dir: "{{ .ANSIBLE_PROJECT_PATH }}/ee"
    cmd: ansible-builder build --container-runtime docker --tag ghcr.io/dbrennand/home-ops:latest -vvv
