---
- name: Download ISOs to Proxmox
  hosts: proxmox
  become: true
  gather_facts: false
  vars:
    # Proxmox directory to store ISOs
    iso_directory: /mnt/pve/ISOs/template/iso
    # ISO URLs to download
    iso_urls:
      - https://example.tld/example-amd64.iso
  tasks:
    - name: Download ISOs
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ iso_directory }}/{{ item | basename }}"
        mode: 755
      loop: "{{ iso_urls }}"
