---
# https://vikunja.io/docs/docker-walkthrough/
# https://vikunja.io/docs/full-docker-example/
version: "3.4"

networks:
  caddy:
    external: true
  vikunja:
    name: vikunja

services:
  vikunja:
    image: docker.io/vikunja/vikunja:0.23.0
    container_name: vikunja
    restart: unless-stopped
    networks:
      - vikunja
      - caddy
    expose:
      - 3456
    volumes:
      - ./files:/app/vikunja/files
      - ./config.yml:/etc/vikunja/config.yml
    depends_on:
      db:
        condition: service_healthy
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.net.dbren.uk
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: vikunja_database
      VIKUNJA_DATABASE_PASSWORD: "${VIKUNJA_DATABASE_PASSWORD}"
      VIKUNJA_DATABASE_USER: "vikunja"
      VIKUNJA_DATABASE_DATABASE: "vikunja"
      VIKUNJA_SERVICE_JWTSECRET: "${VIKUNJA_SERVICE_JWTSECRET}"
    labels:
      caddy: vikunja.{$$DOMAIN}
      caddy.import: cloudflare
      caddy.reverse_proxy: "{{ upstreams 3456 }}"

  db:
    image: docker.io/postgres:16
    container_name: vikunja_database
    restart: unless-stopped
    networks:
      - vikunja
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
    environment:
      POSTGRES_PASSWORD: "${VIKUNJA_DATABASE_PASSWORD}"
      POSTGRES_USER: vikunja
