---
# vars file for playbook

# Pi-hole data directory
pihole_data_directory:
  path: ~/.local/share/pihole
# Pi-hole dnsmasq directory
pihole_dnsmasq_directory:
  path: ~/.local/share/dnsmasq
# Domain name to be used by Pi-hole for the network
# The base/apex domain must be registered with Cloudflare
pihole_domain: net.domain.tld
# A/AAAA records for local DNS
pihole_local_dns:
  - domain: "device.{{ pihole_domain }}"
    ip: "192.168.0.4"
# CNAME records for local DNS
pihole_cname_records:
  - domain: "service.{{ pihole_domain }}"
    target: "device.{{ pihole_domain }}"
# Pi-hole container image tag
pihole_image_tag: latest
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
pihole_timezone: Europe/London
# Pi-hole admin dashboard password
pihole_webpassword: password
# Set to the Pi-hole's local IP address
pihole_ftlconf_local_ip: "192.168.0.2"
# Pi-hole upstream DNS servers
pihole_upstream_dns:
  - "1.1.1.1"
  - "1.0.0.1"
# Pi-hole DHCP settings
# pihole_dhcp_start: "192.168.0.21"
# pihole_dhcp_end: "192.168.0.254"
# pihole_dhcp_router: "192.168.0.1"
# Pi-hole virtual host
pihole_virtual_host: "pihole.{{ pihole_domain }}"
# Whether to enable query logging or not in Pi-hole
pihole_query_logging: "true"
# Pi-hole admin dashboard theme
pihole_web_theme: default-dark

# geerlingguy.security role vars
# https://github.com/geerlingguy/ansible-role-security
security_ssh_allowed_users:
  - "{{ ansible_user }}"
security_sudoers_passwordless:
  - "{{ ansible_user }}"
security_autoupdate_enabled: false
security_fail2ban_enabled: false

# artis3n.tailscale role vars
# https://github.com/artis3n/ansible-role-tailscale
tailscale_authkey: key
tailscale_args: --accept-dns=false --ssh

# geerlingguy.pip role vars
# https://github.com/geerlingguy/ansible-role-pip
pip_install_packages:
  - name: docker

# geerlingguy.docker role vars
# https://github.com/geerlingguy/ansible-role-docker
docker_users:
  - "{{ ansible_user }}"
docker_daemon_options:
  "log-driver": "json-file"
  "log-opts":
    "max-size": "10m"
    "max-file": "3"

# dbrennand.caddy_docker role vars
# https://github.com/dbrennand/ansible-role-caddy-docker
caddy_docker_caddyfile: |-
  {
          email {$ACME_EMAIL}
  }

  # Cloudflare DNS-01 challenge
  (cloudflare) {
          tls {
                  dns cloudflare {$CLOUDFLARE_API_TOKEN}
          }
  }

  pihole.{$DOMAIN} {
          import cloudflare
          reverse_proxy pihole:80
  }
caddy_docker_plugins:
  # Allows Caddy to obtain TLS certificates for a Cloudflare managed domain
  - github.com/caddy-dns/cloudflare
caddy_docker_environment_variables:
  # Variables used in the Caddyfile
  DOMAIN: "{{ domain }}"
  # https://github.com/dbrennand/ansible-role-caddy-docker/blob/main/README.md#example---cloudflare-dns-01-challenge
  CLOUDFLARE_API_TOKEN: token
  # The email address used to receive notifications from Let's Encrypt
  ACME_EMAIL: email@domain.tld
