---
# vars file for setup-playbook.yml
# Name of the user and group to ensure exists
username: daniel
# Packages to install
packages:
  - sudo
  - ncdu
  - htop
  - vim

# geerlingguy.security vars
# https://github.com/geerlingguy/ansible-role-security#role-variables
security_ssh_allowed_users:
  - "{{ username }}"
security_fail2ban_custom_configuration_template: "../templates/jail.local.j2"
