---
# vars file for setup-playbook.yml

# List of packages to install
packages:
  - sudo
  - lm-sensors
  - ncdu
  - htop
  - vim
  - tmux

# geerlingguy.security role vars
# https://github.com/geerlingguy/ansible-role-security#role-variables
security_ssh_allowed_users:
  - "{{ username }}"
security_fail2ban_custom_configuration_template: "../templates/setup/jail.local.j2"
