---
- name: Deploy AWX on K3s
  hosts: k3s01.net.dbren.uk
  tasks:
    - name: Ensure git is installed
      become: true
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone github.com/kurokobo/awx-on-k3s
      ansible.builtin.git:
        repo: https://github.com/kurokobo/awx-on-k3s.git
        dest: "/home/{{ ansible_user }}/awx-on-k3s"
        version: 2.19.1
        force: true

    - name: Deploy AWX Operator
      ansible.builtin.command:
        cmd: "kubectl apply -k /home/{{ ansible_user }}/awx-on-k3s/operator"

    - name: Create PostgreSQL directory
      become: true
      ansible.builtin.file:
        path: /data/postgres-15
        state: directory

    - name: Create AWX projects directory
      become: true
      ansible.builtin.file:
        path: /data/projects
        state: directory
        owner: 1000
        group: 0
