---
- name: K3s | Build cluster
  hosts: k3s
  vars_files:
    - ../vars/k3s.yml
  roles:
    - role: xanmanning.k3s
      tags: k3s
  post_tasks:
    - name: Copy kubeconfig to local machine
      when: k3s_control_node
      block:
        - name: Ensure ~/.kube directory exists
          ansible.builtin.file:
            path: ~/.kube
            state: directory
            mode: u=rwx,g=,o=
          delegate_to: localhost

        - name: Copy kubeconfig from control node to local machine
          ansible.builtin.fetch:
            src: /etc/rancher/k3s/k3s.yaml
            dest: ~/.kube/config
            flat: true

        - name: Replace localhost with control node IP
          ansible.builtin.replace:
            path: ~/.kube/config
            regexp: '127.0.0.1'
            replace: "{{ kube_vip_address }}"
          delegate_to: localhost
