---
- name: LXC | Configure systemd-journald
  hosts: lxc
  become: true
  handlers:
    - name: Restart systemd-journald
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
  tasks:
    - name: Configure systemd-journald SystemMaxUse to 100M
      notify:
        - Restart systemd-journald
      ansible.builtin.lineinfile:
        dest: /etc/systemd/journald.conf
        regexp: '^SystemMaxUse='
        line: 'SystemMaxUse=100M'
        state: present
        backup: true

    - name: Clean apt-cache
      ansible.builtin.apt:
        clean: true
