---
- name: General | Patch Playbook
  hosts: all
  serial: 1
  become: true
  pre_tasks:
    - name: Check if Docker is installed
      register: docker_installed
      ansible.builtin.stat:
        path: /usr/bin/docker

    - name: Stop all Docker containers
      when: docker_installed.stat.exists
      changed_when: false
      ansible.builtin.shell:
        cmd: docker stop $(docker ps -a -q)
  tasks:
    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: List upgradable packages
      changed_when: false
      register: upgradable_packages
      ansible.builtin.command:
        cmd: apt list --upgradable

    - name: Show upgradable packages
      ansible.builtin.debug:
        var: upgradable_packages.stdout_lines

    - name: Update all packages # noqa package-latest
      ansible.builtin.apt:
        name: "*"
        state: latest
        install_recommends: false

    - name: Check if reboot is required
      register: reboot_required
      ansible.builtin.stat:
        path: /var/run/reboot-required

    - name: Reboot if required
      when: reboot_required.stat.exists
      ansible.builtin.reboot:
  post_tasks:
    - name: Start all Docker containers
      when: docker_installed.stat.exists
      changed_when: false
      ansible.builtin.shell:
        cmd: docker start $(docker ps -a -q)
