---
- name: AWX | Register Execution Environment, Credentials, Projects, Inventories and Notification
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    controller_host: awx.net.dbren.uk
    controller_username: "{{ lookup('community.general.onepassword', 'awx.net.dbren.uk', field='username', vault='Home-Ops') }}"
    controller_password: "{{ lookup('community.general.onepassword', 'awx.net.dbren.uk', vault='Home-Ops') }}"
  tasks:
    - name: Register Execution Environment (EE)
      awx.awx.execution_environment:
        name: Home-Ops
        image: ghcr.io/dbrennand/home-ops:latest
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"

    - name: Create Home-Ops AWX Source Control Credential
      awx.awx.credential:
        name: Home-Ops AWX Deploy Key
        description: Home-Ops AWX Deploy Key
        organization: Default
        credential_type: Source Control
        inputs:
          ssh_key_data: "{{ lookup('community.general.onepassword_ssh_key', 'q25yyvantxbo33vyqsnjyabcxi', vault='Home-Ops', ssh_format=true) }}"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create Home-Ops SSH Key Machine Credential
      awx.awx.credential:
        name: Home-Ops SSH Key
        description: Home-Ops SSH Key
        organization: Default
        credential_type: Machine
        inputs:
          ssh_key_data: "{{ lookup('community.general.onepassword_ssh_key', 'jugz6ucagnwgjepx6d6r2j5xem', vault='Home-Ops', ssh_format=true) }}"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create 1Password Service Account Token Credential Type
      tags: op_cred_type
      awx.awx.credential_type:
        name: 1Password Service Account Token
        description: 1Password Service Account Token
        inputs: |
          {
            "fields": [
              {
                "id": "service_account_token",
                "type": "string",
                "label": "1Password Service Account Token",
                "secret": true
              }
            ],
            "required": [
              "service_account_token"
            ]
          }
        injectors: |
          {
            "env": {
              "OP_SERVICE_ACCOUNT_TOKEN": "{% raw %}{{ service_account_token }}{% endraw %}"
            }
          }
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create Home-Ops Project
      awx.awx.project:
        name: Home-Ops
        description: Home-Ops Project
        organization: Default
        credential: Home-Ops AWX Deploy Key
        default_environment: Home-Ops
        scm_type: git
        scm_update_on_launch: true
        scm_url: git@github.com:dbrennand/home-ops.git
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create Home-Ops Inventory
      awx.awx.inventory:
        name: Home-Ops
        description: Home-Ops Inventory
        organization: Default
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create Home-Ops Inventory Source
      awx.awx.inventory_source:
        credential: Home-Ops AWX Deploy Key
        description: Home-Ops Inventory Source
        organization: Default
        name: Home-Ops Inventory Source
        inventory: Home-Ops
        source: scm
        source_path: ansible/inventory/inventory.yml
        source_project: Home-Ops
        update_on_launch: true
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present

    - name: Create Home-Ops Discord Notification Template
      tags: awx_notification
      awx.awx.notification_template:
        name: Home-Ops Discord Webhook
        description: Home-Ops Discord Webhook
        organization: Default
        notification_type: webhook
        notification_configuration:
          url: "{{ lookup('community.general.onepassword', 'Discord Webhook', vault='Home-Ops') }}"
          headers:
            Content-Type: application/json
        messages:
          started:
            body: !unsafe '{"content": "AWX Job {{ job.name }} with ID {{ job.id }} started."}'
          success:
            body: !unsafe '{"content": "AWX Job {{ job.name }} completed in {{ job.elapsed }} seconds."}'
          error:
            body: !unsafe '{"content": "AWX Job {{ job.name }} failed. Investigate logs at {{ job.url }}"}'
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        state: present
