---
- name: Proxmox | Provision LVM Storage
  hosts: proxmox01.net.dbren.uk
  become: true
  vars:
    ssds:
      # Crucial SSD
      - device: /dev/sdb
        partition_name: pv-ssd-crucial
        vg_name: vg-ssd-crucial
        lv_name: lv-ssd-crucial
      # Samsung SSD
      - device: /dev/sdc
        partition_name: pv-ssd-samsung
        vg_name: vg-ssd-samsung
        lv_name: lv-ssd-samsung
  tasks:
    - name: Create | LVM Physical Volume Partition
      loop: "{{ ssds }}"
      community.general.parted:
        device: "{{ item.device }}"
        name: "{{ item.partition_name }}"
        label: gpt
        number: 1
        part_start: 0%
        part_end: 100%
        flags:
          - lvm
        state: present

    - name: Create | LVM Volume Group
      loop: "{{ ssds }}"
      community.general.lvg:
        vg: "{{ item.vg_name }}"
        pvs: "{{ item.device }}1"
        state: present

    - name: Create | LVM Logical Volume
      loop: "{{ ssds }}"
      when: item.lv_name not in ansible_lvm.lvs
      community.general.lvol:
        vg: "{{ item.vg_name }}"
        thinpool: "{{ item.lv_name }}"
        size: 100%FREE
        state: present

    - name: Proxmox | Configure LVM Logical Volumes
      loop: "{{ ssds }}"
      loop_control:
        index_var: index
      ansible.builtin.blockinfile:
        path: /etc/pve/storage.cfg
        backup: true
        marker: "\n# {mark} ANSIBLE MANAGED BLOCK {{ index }}"
        block: |
          lvmthin: {{ item.lv_name }}
                  thinpool {{ item.lv_name }}
                  vgname {{ item.vg_name }}
                  content rootdir,images
        state: present
