---
- name: General | Setup Playbook
  hosts: all
  become: true
  vars_files:
    - ../vars/general.yml
  pre_tasks:
    - name: Ensure packages are installed
      tags: packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        update_cache: true
        cache_valid_time: 3600

    - name: User operations
      tags: user
      block:
        - name: "Ensure group exists | {{ username }}"
          ansible.builtin.group:
            name: "{{ username }}"
            state: present

        - name: "Ensure user exists | {{ username }}"
          ansible.builtin.user:
            name: "{{ username }}"
            groups:
              - sudo
              - "{{ username }}"
            password: "{{ lookup('community.general.onepassword', inventory_hostname, vault='Home-Ops') | password_hash('sha512') }}"
            append: true
            shell: /bin/bash
            state: present

    - name: "Set authorised keys from GitHub | {{ username }}"
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: https://github.com/dbrennand.keys

    - name: "Add user to sudoers | {{ username }}"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        state: present
  roles:
    - role: geerlingguy.security
      tags: security
    - role: ironicbadger.figurine
      tags: figurine
  tasks:
    - name: SSH login script
      tags: ssh
      block:
        - name: Ensure SSH login script is present
          ansible.builtin.template:
            src: ../templates/ssh-discord-notify.sh.j2
            dest: /usr/local/sbin/ssh-discord-notify.sh
            owner: root
            group: root
            mode: "0700"

        - name: Add SSH login script to /etc/pam.d/sshd
          ansible.builtin.lineinfile:
            path: /etc/pam.d/sshd
            line: "session optional pam_exec.so /usr/local/sbin/ssh-discord-notify.sh"
            state: present
