---
- name: Setup Playbook
  hosts: all
  become: true
  vars_files:
    - ../vars/general.yml
  roles:
    - role: ironicbadger.figurine
      tags: figurine
  tasks:
    - name: Include geerlingguy.docker
      tags: docker
      when: inventory_hostname in groups["docker"]
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Include geerlingguy.repo-epel
      when: ansible_facts["os_family"] == "RedHat"
      ansible.builtin.import_role:
        name: geerlingguy.repo-epel

    - name: Update and install packages
      tags: packages
      block:
        - name: Debian | Ensure packages are installed
          when: ansible_facts["os_family"] == "Debian"
          ansible.builtin.apt:
            name: "{{ packages }}"
            update_cache: true
            cache_valid_time: 3600
            state: present

        - name: RedHat | Ensure packages are installed
          when: ansible_facts["os_family"] == "RedHat"
          ansible.builtin.dnf:
            name: "{{ packages }}"
            update_cache: true
            state: present

    - name: SSH login script
      tags: ssh
      block:
        - name: Ensure SSH login script is present
          ansible.builtin.template:
            src: ../templates/setup/ssh-discord-notify.sh.j2
            dest: /usr/local/sbin/ssh-discord-notify.sh
            owner: root
            group: root
            mode: "0700"

        - name: Add SSH login script to /etc/pam.d/sshd
          ansible.builtin.lineinfile:
            path: /etc/pam.d/sshd
            line: "session optional pam_exec.so /usr/local/sbin/ssh-discord-notify.sh"
            state: present
