---
- name: Setup Playbook
  hosts: all
  become: true
  vars_files:
    - ../vars/general.yml
  pre_tasks:
    - name: Ensure packages are installed
      tags: packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        update_cache: true
        cache_valid_time: 3600
  roles:
    - role: ironicbadger.figurine
      tags: figurine
  tasks:
    - name: SSH login script
      tags: ssh
      block:
        - name: Ensure SSH login script is present
          ansible.builtin.template:
            src: ../templates/setup/ssh-discord-notify.sh.j2
            dest: /usr/local/sbin/ssh-discord-notify.sh
            owner: root
            group: root
            mode: "0700"

        - name: Add SSH login script to /etc/pam.d/sshd
          ansible.builtin.lineinfile:
            path: /etc/pam.d/sshd
            line: "session optional pam_exec.so /usr/local/sbin/ssh-discord-notify.sh"
            state: present
