---
all:
  vars:
    ansible_user: daniel
  hosts:
    pihole01.net.dbren.uk:
    pihole02.net.dbren.uk:
      ansible_user: root
    proxmox01.net.dbren.uk:
      ansible_user: root
    proxmox02.net.dbren.uk:
      ansible_user: root
    exit01.net.dbren.uk:
      ansible_user: root
    exit02.net.dbren.uk:
      ansible_user: root
    minecraft.net.dbren.uk:
    control01.net.dbren.uk:
    worker01.net.dbren.uk:
    worker02.net.dbren.uk:
    worker03.net.dbren.uk:
  children:
    docker:
      hosts:
        pihole01.net.dbren.uk:
        minecraft.net.dbren.uk:
    lxc:
      hosts:
        pihole02.net.dbren.uk:
        exit01.net.dbren.uk:
        exit02.net.dbren.uk:
    tailscale:
      vars:
        tailscale_tags:
          - home-ops
      hosts:
        pihole01.net.dbren.uk:
          # Overrides group_vars/tailscale.yml
          tailscale_args: &tailscale_dns |-
            --accept-dns=false --ssh --advertise-routes=192.168.0.2/32,192.168.0.3/32,192.168.0.4/32,192.168.0.5/32
          tailscale_tags:
            - home-ops
            - dns
        pihole02.net.dbren.uk:
          tailscale_args: *tailscale_dns
          tailscale_tags:
            - home-ops
            - dns
        minecraft.net.dbren.uk:
          tailscale_tags:
            - external
        proxmox01.net.dbren.uk:
          tailscale_args: --accept-dns=false --ssh
        proxmox02.net.dbren.uk:
          tailscale_args: --accept-dns=false --ssh
        exit01.net.dbren.uk:
          tailscale_args: --ssh --advertise-exit-node
        exit02.net.dbren.uk:
          tailscale_args: --ssh --advertise-exit-node
    proxmox:
      hosts:
        proxmox01.net.dbren.uk:
        proxmox02.net.dbren.uk:
    k3s:
      children:
        control:
          hosts:
            control01.net.dbren.uk:
        workers:
          hosts:
            worker01.net.dbren.uk:
            worker02.net.dbren.uk:
            worker03.net.dbren.uk:
