---
all:
  vars:
    ansible_user: daniel
  hosts:
    pihole.net.dbren.uk:
    pihole02.net.dbren.uk:
      ansible_user: root
    proxmox01.net.dbren.uk:
      ansible_user: root
    proxmox02.net.dbren.uk:
      ansible_user: root
    minecraft.net.dbren.uk:
    control01.net.dbren.uk:
    worker01.net.dbren.uk:
    worker02.net.dbren.uk:
    worker03.net.dbren.uk:
  children:
    docker:
      hosts:
        pihole.net.dbren.uk:
        minecraft.net.dbren.uk:
    tailscale:
      vars:
        tailscale_tags:
          - home-ops
      hosts:
        pihole.net.dbren.uk:
          # Overrides group_vars/tailscale.yml
          tailscale_args: --accept-dns=false --ssh
          tailscale_tags:
            - home-ops
            - dns
        pihole02.net.dbren.uk:
          tailscale_args: --accept-dns=false --ssh
          tailscale_tags:
            - home-ops
            - dns
        minecraft.net.dbren.uk:
          tailscale_tags:
            - external
        proxmox01.net.dbren.uk:
          tailscale_args: --accept-dns=false --ssh
        proxmox02.net.dbren.uk:
          tailscale_args: --accept-dns=false --ssh
    proxmox:
      hosts:
        proxmox01.net.dbren.uk:
        proxmox02.net.dbren.uk:
    k3s:
      children:
        control:
          hosts:
            control01.net.dbren.uk:
        workers:
          hosts:
            worker01.net.dbren.uk:
            worker02.net.dbren.uk:
            worker03.net.dbren.uk:
