# https://github.com/TwiN/gatus
version: "3.9"

networks:
  caddy:
    external: true
  gatus:
    name: gatus

services:
  gatus:
    image: twinproduction/gatus:v5.8.0
    container_name: gatus
    restart: unless-stopped
    networks:
      - gatus
      - caddy
    expose:
      - 8080
    volumes:
      - ./config:/config
      - ./data:/data/
    labels:
      caddy: gatus.{$$DOMAIN}
      caddy.import: cloudflare
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
