---
collections:
  - name: community.docker
    version: 3.4.8
roles:
  - name: dbrennand.autorestic
    version: 1.3.1
  - name: dbrennand.caddy_docker
    version: 3.0.2
  - name: artis3n.tailscale
    version: v4.2.2
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.pip
    version: 2.2.0
