---
name: Build Execution Environment
on:
  workflow_dispatch: # Allows manual execution
  push:
    branches:
      - main
    paths:
      - ansible/ee/**

jobs:
  build:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get short SHA commit hash
        id: short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.7"

      - name: Install dependencies
        run: uv sync --group build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        id: docker_buildx
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build Execution Environment image
        working-directory: ansible/ee
        env:
          SHORT_SHA: ${{ steps.short_sha.outputs.SHORT_SHA }}
          BUILDX_NAME: ${{ steps.docker_buildx.outputs.name }}
        run: |
          uv run ansible-builder build -vvv --container-runtime docker \
            --tag "ghcr.io/dbrennand/home-ops:${SHORT_SHA}" \
            --extra-build-cli-args "--load --builder ${BUILDX_NAME} --platform linux/amd64,linux/arm64"

      - name: Determine the ID of the Execution Environment image
        id: ee_id
        env:
          SHORT_SHA: ${{ steps.short_sha.outputs.SHORT_SHA }}
        run: echo "IMAGE_ID=$(docker images -q "ghcr.io/dbrennand/home-ops:${SHORT_SHA}")" >> $GITHUB_OUTPUT

      - name: Create the latest tag
        env:
          IMAGE_ID: ${{ steps.ee_id.outputs.IMAGE_ID }}
        run: docker tag "${IMAGE_ID}" "ghcr.io/dbrennand/home-ops:latest"

      - name: Push Execution Environment image to GitHub Container Registry
        env:
          SHORT_SHA: ${{ steps.short_sha.outputs.SHORT_SHA }}
        run: |
          docker push ghcr.io/dbrennand/home-ops:latest
          docker push "ghcr.io/dbrennand/home-ops:${SHORT_SHA}"
